version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "5.0.x"
    commit-message:
      prefix: "[5.0.x] "
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "javax.servlet:javax.servlet-api"
        versions: [ ">=4.0.0" ]
      - dependency-name: "javax.websocket:javax.websocket-client-api"
        versions: [ ">=1.1" ]
      - dependency-name: "javax.websocket:javax.websocket-api"
        versions: [ ">=1.1" ]
      - dependency-name: "com.google.inject:guice"
        versions: [ ">=7.0.0" ]
      - dependency-name: "com.google.javascript:closure-compiler"
        versions: [ ">=v20220502" ]
      - dependency-name: "org.graalvm.js:js"
        versions: [ ">=21.3.2.1" ]
      - dependency-name: "org.springframework:*"
        versions: [ ">=6.0.0" ]
      - dependency-name: "org.springframework.boot:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "org.asciidoctor:asciidoctor-maven-plugin"
        versions: [ ">=3.0.0" ]
      - dependency-name: "org.apache.felix:maven-bundle-plugin"
        versions: [ ">=6.0.0" ]
      - dependency-name: "com.mycila:license-maven-plugin"
        versions: [ ">=5.0.0" ]
      - dependency-name: "com.squareup.okhttp3:okhttp"
        versions: [ ">=5.0.0" ]
      - dependency-name: "com.diffplug.spotless:spotless-maven-plugin"
        versions: [ ">=2.30.0" ]
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        versions: [ ">=6.0.0" ]

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "6.0.x"
    commit-message:
      prefix: "[6.0.x] "
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.google.inject:guice"
        versions: [ ">=7.0.0" ]
      - dependency-name: "com.google.javascript:closure-compiler"
        versions: [ ">=v20240317" ]
      - dependency-name: "org.graalvm.js:js"
        versions: [ ">=23.0.0" ]
      - dependency-name: "org.springframework:*"
        versions: [ ">=6.0.0" ]
      - dependency-name: "org.springframework.boot:*"
        versions: [ ">=3.0.0" ]
      - dependency-name: "org.apache.felix:maven-bundle-plugin"
        versions: [ ">=6.0.0" ]
      - dependency-name: "com.squareup.okhttp3:okhttp"
        versions: [ ">=5.0.0" ]
      - dependency-name: "com.diffplug.spotless:spotless-maven-plugin"
        versions: [ ">=3.0.0" ]
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        versions: [ ">=6.0.0" ]

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "8.0.x"
    commit-message:
      prefix: "[8.0.x] "
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "jakarta.platform:jakarta.jakartaee-bom"
        versions: [ ">=11.0.0" ]
      - dependency-name: "org.eclipse.jetty:*"
        versions: [ ">=12.1.0" ]
      - dependency-name: "org.springframework:*"
        versions: [ ">=7.0.0" ]
      - dependency-name: "org.springframework.boot:*"
        versions: [ ">=4.0.0" ]

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "9.0.x"
    commit-message:
      prefix: "[9.0.x] "
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
